foreground   #decde4
background   #0d0d19
cursor       #decde4

color0       #0d0d19
color8       #9b8f9f
color1       #716CCB
color9       #716CCB
color2       #9373BA
color10      #9373BA
color3       #7984D1
color11      #7984D1
color4       #DD9E9C
color12      #DD9E9C
color5       #A197DD
color13      #A197DD
color6       #AEA0C0
color14      #AEA0C0
color7       #decde4
color15      #decde4
